# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: eb589fd866803231d8485e2be4b833edee8695e1d75d063c4e97e473fa2f5247de9dd6e66a47a73d2085b4ad57ef33988f8adada66de72a8b5dbe99b6d438198

test:
  secret_key_base: 2a2f7368c5ad3de3c6994e54c1e30ccf5e386a570aef9860d6b628688128ac312a6054f00c08095737e1626f50ff47fe147c088dfbf182ba98cb7899093de43a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
